server:
  contextPath: /flights
externalServices:
  routesUrl: https://api.ryanair.com/core/3/routes
  schedulesUrl: https://api.ryanair.com/timetable/3/schedules/{departure}/{arrival}/years/{year}/months/{month}